# Introduction {.unnumbered}

In order to get the most out of the APTS module on Statistical
Modelling, students should have, at the start of the module, a sound
knowledge of the principles of statistical inference and the theory of
linear and generalised linear models. Students should also have some
experience of statistical modelling in R.

The following reading and activities are recommended to all students
to (re)-familiarise themselves with those topics.

**Statistical inference**: It is recommended that students (re)-read
the notes of the APTS module on Statistical Inference, available from
the [APTS website](https:/apts.ac.uk), and complete the assessment
exercise (if they have not already done so). No further material is
provided here.

**Linear and generalised linear models**: A student who has covered
@davison:2003 [Chapters 8 and 10.1-10.4] will be more than adequately
prepared for the APTS module. For students without access to this
book, the main theory is repeated in the current set of notes. The
inference methodology described is largely based on classical
statistical theory. Although prior experience of Bayesian statistical
modelling would be helpful, it will not be assumed.

**Preliminary material exercises**: Nine exercises are included in the
current preliminary material.

**R practicals**: Some practical exercises are also provided at the
end of these notes to enable students to familiarise themselves with
statistical modelling in R.

## Typos and issues {.unnumbered}

You can report and suggest fixes to typos and issues by opening a new
issue at the GitHub repository hosting the preliminary material. The repository
can be accessed [here](https://github.com/APTS-Statistical-Modelling/APTS-SM-Preliminary/issues/new).
If you are reading the HTML version of this notes you can directly report an issue by clicking
[Report an issue](https://github.com/APTS-Statistical-Modelling/APTS-SM-Preliminary/issues/new)
on the right-hand-side panel. You can also suggest the edit directly
by following the instructions after clicking "Edit this page".


## Acknowledgements {.unnumbered}

This set of notes is an editted version of material developed by
previous module leaders of the APTS Statistical Modelling
module. These are (in reverse chronological order)

| Name                                                                                     | Affiliation               |
|------------------------------------------------------------------------------------------|---------------------------|
| [Helen Ogden](https://www.southampton.ac.uk/people/5xhjnm/doctor-helen-ogden)            | University of Southampton |
| [Antony Overstall](http://www.personal.soton.ac.uk/amo105/)                              | University of Southampton |
| [Dave Woods](https://www.southampton.ac.uk/people/5wz6hb/professor-dave-woods)           | University of Southampton |
| [Jon Forster](https://warwick.ac.uk/fac/sci/statistics/staff/academic-research/forster/) | University of Warwick     |
| [Anthony Davison](https://people.epfl.ch/anthony.davison)                                | EPFL                      |
: {tbl-colwidths="[40,30]"}
